### ISSUE TITLE
Retirer les trucs inutiles dans settings.py

### ISSUE THREAD

**Issue by agateblue** [entropyqueen/trans-cec#1]
- [x] L'application n'utilise pas de base données, on peut enlever https://github.com/entropyqueen/trans-cec/blob/deploy/mysite/mysite/settings.py#L95-L100 (remplacer par un dico vide) et s'épargner le `python manage.py migrate`
- [x] On peut enlever les applications et middelwares liés à l'authentification, aux contenttypes, à l'admin :
  - https://github.com/entropyqueen/trans-cec/blob/deploy/mysite/mysite/settings.py#L28-L30
  - https://github.com/entropyqueen/trans-cec/blob/deploy/mysite/mysite/settings.py#L43
- [x] à confirmer, je crois que l'application ne stocke rien en session (y'a quelques trucs en local storage de mémoire), https://github.com/entropyqueen/trans-cec/blob/deploy/mysite/mysite/settings.py#L31 et https://github.com/entropyqueen/trans-cec/blob/deploy/mysite/mysite/settings.py#L40 peuvent s'en aller. (tester l'app quand même après avoir enlevé ça)
- [x] pas d'authentification, pas de mots de passe, on peut enlever https://github.com/entropyqueen/trans-cec/blob/deploy/mysite/mysite/settings.py#L106-L119 
- [x] à tester, j'ai l'impression qu'on utilise le moteur de template jinja et pas celui de django. Si c'est bien le cas, on peut enlever https://github.com/entropyqueen/trans-cec/blob/deploy/mysite/mysite/settings.py#L74-L86

**Comment by trpyn** [comment]
All done, merci pour ta  review !
