### ISSUE TITLE
Ajout du livret de famille à la checklist

### ISSUE THREAD

**Issue by xenolune** [entropyqueen/trans-cec#14]
> La mise à jour du livret de famille est obligatoire en cas de changement dans votre état civil (nom, prénom, sexe) ou situation de famille (mariage, séparation, naissance, adoption, divorce, décès,..). C'est à vous (la personne qui possède l'original du livret de famille) d'effectuer, dans les meilleurs délais, les démarches pour y faire inscrire ces changements. 
https://www.service-public.fr/particuliers/vosdroits/F18910

C'est important si l'on a des enfants !

**Comment by trpyn** [comment]
Bien vu, merci beaucoup ! C'est rajouté :)
