### ISSUE TITLE
Mauvais contacts et repo

### ISSUE THREAD

**Issue by juin-en-anglais** [entropyqueen/trans-cec#6]
Hello, j’ai vu un truc qui peut amener à de menus problèmes dans le futur.

- Le contact en cas d’erreur est relié à Sasha Emily Chelsea Murgia, alors que cette version est reliée à une autre personne.
- L’adresse du repertoire ramène à [Gitlab](http://gitlab.chelsea486mhz.fr/Chelsea486MHz/trans-cec), plutôt qu’ici.

Merci d’avoir remis ce service en ligne!

**Comment by trpyn** [comment]
Fixé, merci pour ton attention !
