### ISSUE TITLE
Courriers EDF fait une erreur 500

### ISSUE THREAD

**Issue by trpyn** [entropyqueen/trans-cec#9]

**Comment by Sk8erOfBodom** [comment]
C'est pas la seule page, il y a toutes celles là :
- /procuration/edf/
- /procuration/assurance/
- /procuration_relance/edf/
- /procuration/assurance/
- /procuration_relance/assurance/
- /procuration_relance/poleemploi/
- /procuration_relance/conciliateurcpam/

**Comment by trpyn** [comment]
Il s'agit à priori de la même erreur partout, c'est un KeyError 

```
Environment:


Request Method: GET
Request URL: http://127.0.0.1:8000/procuration/assurance/

Django Version: 4.1.3
Python Version: 3.10.6
Installed Applications:
['django.contrib.staticfiles', 'django_tex', 'pdfgenerator']
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware']



Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/app/web/pdfgenerator/views.py", line 34, in form
    form_config = forms.REGISTERED_FORMS[form_id]

Exception Type: KeyError at /procuration/assurance/
Exception Value: 'procuration_assurance'
```

Oui, donc en fait les clés du dico sont générées dans https://github.com/entropyqueen/trans-cec/blob/05345c238048c833060f89c364e72cf97fe01ff6/mysite/pdfgenerator/forms.py#L67 

Il s'agit d'un décorateur appliqué sur les class formulaires, comme par exemple:
```python
@register_form(category='procuration_relance', id="banque", title="Relance pour une Banque", url='procuration/relance/banque')
class BanqueRelanceProcuration(RelanceProcurationForm, BanqueProcuration):
    pass
```

Il faut donc créer celles qui manquent ; par contre du coup je ne suis pas certaine de si ça celles qui sont créées vide fonctionnent... 
- [ ] à checker qu'elles fonctionnent
- [ ] créer les class manquantes

**Comment by trpyn** [comment]
Commit 78afe076106bfe17502db61b427fa083cd4eac8a remplace les erreurs 500 par des 404, il faut créer les templates et formulaire pour les pages qui marchent pas, issue recréée sous #18
